from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
BASE_DIR = PROJECT_ROOT / "baseCase"
CASE_DIR = Path("/tmp/ramdisk/case")
TMP_DIR = Path("/tmp/ramdisk/tmp")
RESULTS_DIR = PROJECT_ROOT / "results"

MESH_WIDTH = 0.07
MESH_HEIGHT = 0.0255
MESH_DEPTH = 0.02
MESH_DENSITY = 5
MESH_CENTER = [0, -0.0625, 0.015]
MESH_UNIT = 'm'

POPULATION_SIZE = 20
NUM_GENERATIONS = 50
MUTATION_FACTOR = 0.2

PARALLEL_EVALUATIONS = 5
CORES_PER_CFD = 6

MUTATION_RATE = 0.3
MUTATION_STRENGTH = 0.004

MIN_WING_DIMENSIONS = {
    'x': 0.01,
    'y': 0.005,
    'z': 0.002
}

DIMENSION_PENALTY_WEIGHT = 10000.0
VOLUME_REWARD_WEIGHT = 1.0
SMOOTHNESS_REWARD_WEIGHT = 70.0
CD_WEIGHT = 1000.0
EXPECTED_VOLUME_RANGE = [1e-6, 1e-4]