from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
BASE_DIR = PROJECT_ROOT / "baseCase"
CASE_DIR = PROJECT_ROOT / "case"
TMP_DIR = PROJECT_ROOT / "tmp"
RESULTS_DIR = PROJECT_ROOT / "results"

MESH_WIDTH = 0.07
MESH_HEIGHT = 0.0255
MESH_DEPTH = 0.02
MESH_DENSITY = 5
MESH_CENTER = [0, -0.0625, 0.015]
MESH_UNIT = 'm'

POPULATION_SIZE = 75
NUM_GENERATIONS = 30
MUTATION_FACTOR = 0.2

MUTATION_RATE = 0.3
MUTATION_STRENGTH = 0.004